### PR TITLE
Propagate errors from neat_addr_update_src_list

### PR DESCRIPTION
**Pull request by bagder**
Baby steps. Made neat_addr_update_src_list return error code and propagate that up the chain, primarily for OOM errors.

### CODE REVIEW

**Comment by oystedal** [comment]
Sorry about the time it has taken to check this.

Does not compile on BSD, http://buildbot.nplab.de:28010/builders/freebsd-11-x64/builds/410/steps/compile/logs/stdio, typo `net_error_code` on line 176: https://github.com/NEAT-project/neat/pull/142/files#diff-63da37fd7113f0a04b30054ef0658b2dR176

**Comment by bagder** [comment]
Stupid typo (and I have no BSD machine to test build on). Fixed now, I think.

**Comment by oystedal** [comment]
Hm, BSD-bots still complaining: http://buildbot.nplab.de:28010/builders/freebsd-11-x64/builds/411/steps/compile/logs/stdio. I only glanced quickly over the previous log for the first error and failed to notice these as well.

Anyway, I can fix the remaining errors either tonight or tomorrow morning, considering I have a FreeBSD VM at hand.

**Comment by bagder** [comment]
Ah yes, `neat_bsd_route_recv` needs to match the proto that libuv sets as it is a callback for libuv so this change isn't a good one.

Either we ignore errors in the callback or we need to use some other mechanism to terminate the libuv loop.

**Comment by naeemk** [comment]
@bagder @oystedal any update on this? I see it's already in conflict zone :)

**Comment by oystedal** [comment]
This PR is now part of #177, closing.

**Pull request closed without merging**
