### PR TITLE
prefix: rename private global functions to use nt_ prefix

### LINKED ISSUE #141: Prefix for private global symbols
(Possibly related to coding style, issue #94)

I propose we use a dedicated and identifiable prefix for functions/symbols that are globally accessible within the library but _aren't_ in the public API. Right now, they're all prefixed with `neat_`. Having this fact notable is helpful as the public API must remain stable etc while the internal can be changed much easier.

I propose we use `neat__` (with two underscores) or `Neat_` (with uppercase N) for the private global symbols.

### PR DESCRIPTION
**Pull request by bagder**
... and save neat_ for functions that are externally visible.

'nt_' was selected as short version of neat.

Mentioned on the mailing list 10 Aug 2017.

Fixes #141

### CODE REVIEW

**Comment by weinrank** [comment]
Since there are some branches out there which are still under development and can't be merged instantly: Can you provide the SED file and a small tutorial, how to apply these changes for existing branches?

**Comment by bagder** [comment]
Good idea, added a script with embedded docs.

**Comment by weinrank** [comment]
If nobody complains, ready to merge?

**Comment by bagder** [comment]
Squashed and rebased. Will merge once travis says green.

**Pull request closed without merging**
