### PR TITLE
New Happy Eyeballs

### PR DESCRIPTION
**Pull request by oystedal**
By popular demand, here's the new HE implementation. :tada: 

The HE code is written by @karlgrin, while I have written some new interfacing code from the NEAT logic. @tuexen also provided a much appreciated bugfix.

Feel free to give it a spin on all your weird and exotic network setups. Unless someone complains we'll merge it early next week.

### CODE REVIEW

**Comment by tuexen** [comment]
I did some testing and found one issue: You use `connect()` calls on non-blocking sockets and then fire a callback, once the socket becomes writable. If this happens the first time, you select the socket and stop the selection. At least this is my understanding.

However, if the connection setup breaks, because you get a TCP reset segment, and SCTP ABORT chunks, or an ICMP message indicating a hard error, the socket also becomes writable (it also becomes readable, but it seems that this isn't taken into account).

To reproduce this, make sure connection setup breaks and you have more than one candidate. You should actually try all of them and only fail the flow setup if none of the candidates work.

I found this bug in a scenario, where I'm running FreeBSD with only IPv4 in a VMWare VM using a NATed interface. So TCP/IPv4 and SCTP/IPv4 are the candidates, SCTP gets tested first, the NAT implementation of the VMWare injects an ICMP message indicating that SCTP is not supported, the SCTP treats this similar to the reception of an ABORT, therefore the association setup fails. However, TCP/IPv4 is not tested.

Here is a log of running `examples/client_http_get bsd10.fh-muenster.de`:

```
Opened flow 0
[   0.007597][DBG] neat_start_event_loop
[   1.015338][DBG] open_resolve_cb
[   1.015523][DBG] HE Candidate  0:      em0 [ 1]     SCTP/IPv4 <saddr 192.168.115.183> <dstaddr 212.201.121.100> port    80 priority 0
[   1.015535][DBG] HE Candidate  1:      em0 [ 1]      TCP/IPv4 <saddr 192.168.115.183> <dstaddr 212.201.121.100> port    80 priority 1
[   1.015544][DBG] HE will now commence


[   1.015553][DBG] neat_connect
[   1.015651][INF] neat_connect: Bind fd 35 to 192.168.115.183
[   1.015861][DBG] neat_he_open: Connect successful for fd 35, ret = 0
[   1.016596][DBG] Invokation count: 1
[   1.016659][DBG] HE Candidate connected:      em0 [ 1]     SCTP/IPv4 <saddr 192.168.115.183> <dstaddr 212.201.121.100> port    80 priority 0
[   1.016677][DBG] First successful connect
[   1.016703][DBG] uvpollable_cb
[   1.016719][DBG] io_connected
[   1.016737][INF] Connected: SCTP/IPv4
[   1.016752][DBG] neat_set_operations
[   1.016791][DBG] updatePollHandle
[   1.016811][DBG] io_writable
[   1.016830][DBG] neat_write
[   1.016846][DBG] neat_write_to_lower_layer
[   1.016912][DBG] neat_write_flush
[   1.016958][DBG] -1 bytes sent on stream 0
on_error
```
I guess, you can see the same problem on a machine with IPv4 and IPv6 addresses and choosing a destination where there is no server running at the port. Not all candidates will be tested.

**Comment by tuexen** [comment]
I have another comment: Is `SCTP/UDP` supported? I saw a commit disabling it. Is there a problem with it?

**Comment by oystedal** [comment]
Disabling SCTP/UDP was a debugging measure, and it proved to be a dead end. I'll revert that commit before a merge.

I'll have a closer look at the logic when the socket becomes writable. I'm going to move some of the code from `neat_core.c` to `neat_he.c`, so that the entire HE code becomes a little more coherent.

**Comment by tuexen** [comment]
Thanks for adding `SCTP/UDP` back.

You might want to check if the socket is also readable and then `read()` to get the possible error indication. Or you can use `getsockopt(..., SOL_SOCKET, SO_ERROR, ..., ...)` to check if there are pending socket errors. If there are, don't consider the connection setup successful.

**Comment by oystedal** [comment]
We have decided to merge this despite the reported issue. This case is probably not handled correctly by the existing HE implementation either, and a lot of progress is blocking on this merge.

**Comment by tuexen** [comment]
That is fine, as long as it gets fixed.

**Comment by karlgrin** [comment]
I have tested Tuexens bug, and it seems that Linux (Linux ubuntu 4.4.0-31-generic) in the same scenario as was tested with FreeBSD, returns a status of -9 (bad file descriptor?) and thus continue
with TCP/IPv4. Why does FreeBSD return status = 0 (i.e., file descriptor writable)? Not sure I understand this difference between OSes.

**Comment by tuexen** [comment]
Where comes the status of -9 from?

I think you call `socket()`, make the fd non-blocking, possibly call `bind()`, and finally call `connect()`. Whether `connect()` returns an error or not is a timing issue. If talking to a remote system, it will not fail. Once the TCP RST, SCTP ABORT, ICMP, or whatever error indication you have, is received, the corresponding socket become readable and writable in `select()`. The readable part means that you can read something, which you should do and the kernel would give you the error indication.

**Pull request merged**
