### PR TITLE
MPTCP support

### PR DESCRIPTION
**Pull request by perhurt**
Adds MPTCP as a separate protocol in NEAT. Tested and verified to work by me and @karlgrin 

## Open issues
- the code in general (improvements, ...),
- the inclusion of MPTCP as a protocol instead of a TCP option

We'd like to discuss (preferably face-to-face in Paris) whether MPTCP should be a separate protocol or only a option to TCP. In this pull request it's a separate protocol. The main motivation behind this is that MPTCP brings a lot of functionality/issues to the table, and that it might be easier to deal with them if MPTCP is a separate protocol.

### CODE REVIEW

**Comment by weinrank** [comment]
Why did you add another example for a http client?
Are there more differences than the property?

**Comment by perhurt** [comment]
No, there aren't any other differences. I actually didn't intend to include that file in the commit, I only used it for testing things. Sorry!

**Comment by naeemk** [comment]
The "open issues" were discussed in Paris, so can we merge this once the conflicts are resolved by @perhurt (and the extra example file removed)?

**Comment by weinrank** [comment]
Is everybody fine if I remove the extra file and merge it into the master?

**Comment by perhurt** [comment]
I'd be perfectly fine with that!

**Comment by weinrank** [comment]
@naeemk *within an hour* !!!

**Pull request merged**
