### PR TITLE
Added jansson dependency

### PR DESCRIPTION
**Pull request by oystedal**
Hi.

I am publishing this pull request as a heads up to everyone that jansson should be installed since this will, following the positive feedback from #82, be a dependency in the future. The latest release, version 2.7 may be downloaded from: http://www.digip.org/jansson/releases/jansson-2.7.tar.gz. The latest development version may be fetched from: https://github.com/akheron/jansson. This library may also be present in various package managers.

I advise everyone to install jansson and to checkout the jansson-dependency branch and try to compile NEAT to ensure that merging this change into the master branch will go smoothly.

My suggestion is to keep this pull request open for a week or two such that everyone is given due notice about the new dependency and given sufficient opportunity to install it and ensure that NEAT still compiles for them. I feel it should not be merged into the master branch before the buildbots are updated to include this dependency. @weinrank, can you eventually take care of this?

- Øystein

### CODE REVIEW

**Comment by weinrank** [comment]
Hey,

yeah i will update the buildbots soon (today?) and tell you when i'm done. 👍

**Comment by kristahi** [comment]
Ubuntu/Debian package: libjansson-dev
FreeBSD port: jansson
NetBSD package: jansson-2.7

**Comment by weinrank** [comment]
All BBs have jansson installed.

After updating some binaries i have dependency issues on the FreeBSD ARM BB - this is not related to jansson. I will fix this on monday.

greetings

**Comment by weinrank** [comment]
FreeBSD ARM is fixed

**Comment by kristahi** [comment]
Any objections to merging this? Upcoming NEAT logic BB PR will depend on it.

**Comment by weinrank** [comment]
@kristahi For me it's fine

**Pull request merged**
