### PR TITLE
Ubuntu PPA packaging

### PR DESCRIPTION
**Pull request by dreibh**
Added make target "dist" to create a tarball.

Ubuntu PPA packaging scripts to automatically generate NEAT packages for all recent Ubuntu variants => https://launchpad.net/~dreibh/+archive/ubuntu/ppa/+packages?field.name_filter=neat&field.status_filter=published&field.series_filter=

### CODE REVIEW

**Comment by oystedal** [comment]
Would it be possible to use `libneat` as the package name instead?

Other than that, it looks good to me.

**Comment by dreibh** [comment]
Okay, changed.

**Comment by oystedal** [comment]
I'll merge this later today unless someone objects to  it.

**Comment by dreibh** [comment]
Merged current master branch. Is there anything to do before the pull request can be merged?

**Comment by oystedal** [comment]
Sorry about the delay.

Out of curiosity, is the PPA updated automatically to the latest version, or does it have to be "repackaged" manually whenever one wants to push a new version?

**Comment by dreibh** [comment]
Hi,

Mandag 21. november 2016 04.54.21 skrev oystedal:
> Sorry about the delay.
> 
> Out of curiosity, is the PPA updated automatically to the latest version, or does it have to be "repackaged" manually whenever one wants to push a new version?

I need to update the version (in debian/changelog and CMakeLists.txt). Then, I have to call "make-ppa" to build and upload the packages for the different Ubuntu distributions. It would in fact be easy to automatise these steps as well. It would just be necessary to ensure that debuild has access to my GnuPG private key, since the packages need to be signed for uploading.

-- 
Best regards / Mit freundlichen Grüßen / Med vennlig hilsen

=======================================================================
 Thomas Dreibholz

 Simula Research Laboratory
 Simula Innovation AS, Network Systems Group
 Visiting address: Martin Linges vei 17, 1364 Fornebu, Norway
 Mailing address:  P.O.Box 134, 1325 Lysaker, Norway
-----------------------------------------------------------------------
 E-Mail:     dreibh@simula.no
 Homepage:   http://simula.no/people/dreibh
=======================================================================

**Comment by kristrev** [comment]
What is the purpose of introducing autotools into NEAT when CMake already provides facilities for creating packages?

**Comment by dreibh** [comment]
Hi,

Mandag 21. november 2016 05.38.14 skrev Kristian Evensen:
> What is the purpose of introducing autotools into NEAT when CMake already provides facilities for creating packages?

The NEAT package does not need autotools. It is probably installed as a dependency of a package NEAT depends on, may be debhelper?

-- 
Best regards / Mit freundlichen Grüßen / Med vennlig hilsen

=======================================================================
 Thomas Dreibholz

 Simula Research Laboratory
 Simula Innovation AS, Network Systems Group
 Visiting address: Martin Linges vei 17, 1364 Fornebu, Norway
 Mailing address:  P.O.Box 134, 1325 Lysaker, Norway
-----------------------------------------------------------------------
 E-Mail:     dreibh@simula.no
 Homepage:   http://simula.no/people/dreibh
=======================================================================

**Comment by kristrev** [comment]
Yes, I edited my question as I meants tools, not autotools :) I am talking about autogen.sh, etc.

**Comment by oystedal** [comment]
As far as I have understood, these scripts only creates the package, building NEAT is still left to CMake.

As a side note, it would be nice if it could pull as much data as possible from CMake so that these packaging scripts doesn't have to be updated for every new release.

**Comment by kristrev** [comment]
https://cmake.org/Wiki/CMake:CPackPackageGenerators

**Comment by dreibh** [comment]
Hi,

Mandag 21. november 2016 07.01.12 skrev oystedal:
> As far as I have understood, these scripts only creates the package, building NEAT is still left to CMake.

Yes, the scripts are only for automatically creating and PPA-uploading the Ubuntu/Debian packages. They are not needed for building NEAT in general.


> As a side note, it would be nice if it could pull as much data as possible from CMake so that these packaging scripts doesn't have to be updated for every new release.

The scripts (like make-deb, make-ppa, clean-deb, etc.) are fixed, i.e. no need for an update.

For tarball releases, it would even be possible to exclude these scripts. I can add them to CPACK_SOURCE_IGNORE_FILES.

-- 
Best regards / Mit freundlichen Grüßen / Med vennlig hilsen

=======================================================================
 Thomas Dreibholz

 Simula Research Laboratory
 Simula Innovation AS, Network Systems Group
 Visiting address: Martin Linges vei 17, 1364 Fornebu, Norway
 Mailing address:  P.O.Box 134, 1325 Lysaker, Norway
-----------------------------------------------------------------------
 E-Mail:     dreibh@simula.no
 Homepage:   http://simula.no/people/dreibh
=======================================================================

**Pull request merged**
