### PR TITLE
NEAT Sockets API

### PR DESCRIPTION
**Pull request by dreibh**
This is the NEAT Sockets API pull request, including examples and documentation.

Available so far:
- Socket operations, blocking and non-blocking with poll()/select().
- Wrapper-code for handling non-NEAT sockets.
- Examples: HTTP client, HTTP servers (single socket, multi-socket with select(), multi-socket with threads)
- Packaging and builds for Ubuntu/Debian and Fedora
=> API is ready useful for most application cases

Future work (will *not* be part of this pull request):
- TLS security (requires TLS to work in NEAT Callback API; API details to be discussed)
- Notifications (notification queue is already implemented)

### CODE REVIEW

**Comment by bagder** [comment]
Sorry but you should submit this as a series of smaller pull requests and imho you should try to clarify the commit messages better. This is just too massive to review in a single go.

**Comment by dreibh** [comment]
How do you suggest the pull request to be splitted up?

Note, that the few small changes to the NEAT Callback API are already separated as https://github.com/NEAT-project/neat/pull/304 and https://github.com/NEAT-project/neat/pull/298 (they are already merged in my Sockets API pull request, since they are required for building).

The rest of the Sockets API code is new under socketapi/. It does not make sense to split up the code there. The only thing possible would be to separate socketapi/examples/ (which then depends on the Sockets API, of course) and socketapi/docs (only some XML files; no dependency).

**Comment by bagder** [comment]
1. You could squash commits so that there aren't that many "updates" and "fixes" to previous commits. We don't need to see the development of these things, we want to review the result you want to merge.
2. I would then suggest you rebase the entire patch set to get rid of the large number of merge commits.

That should reduce the number of commits pretty good. As for ways to split it up logically, I don't know enough of your work to tell you how or if that is possible. Most things can however be divided into smaller chunks...

**Comment by weinrank** [comment]
Does not compile on any platform except Ubuntu...

**Comment by weinrank** [comment]
Platforms:
* FreeBSD stable
* FreeBSD head
* FreeBSD arm
* NetBSD
* Mac OS

see: http://buildbot.nplab.de:28010/waterfall?branch=dreibh/neat-socketapi

> I do not use MacOS.  

It's never too late....

**Comment by dreibh** [comment]
FreeBSD and NetBSD are working now.

Is the build bot (http://buildbot.nplab.de:28010/waterfall?branch=dreibh/neat-socketapi) not working again? The last time I looked for the MacOS problems, it showed some linker problems. MacOS probably requires some work-around in the CMake files, but I have no possibility to examine this further.

**Comment by weinrank** [comment]
The buildbots are working great! 💪 

The website only shows the most recent builds, if you want to rebuild your branch:

1. select `Builders` in the top menu
2. scroll down to the `Force All Builds` section
3. type in your branch name in the `branch` input field - in your case `dreibh/neat-socketapi`
4. click `Force Build`
5. wait for the results :)

http://buildbot.nplab.de:28010/builders/osx/builds/1705/steps/compile/logs/stdio
There's the output you're looking for.

**Comment by dreibh** [comment]
The MacOS build problem is also fixed now.

**Comment by weinrank** [comment]
Buildbots are fine - can't say much about the code.

**Pull request merged**
