### PR TITLE
Karlgrin/he pm 161128

### PR DESCRIPTION
**Pull request by karlgrin**
@oystedal @bozakov Complemented result from HE with candidate properties.

### CODE REVIEW

**Comment by oystedal** [comment]
Seems fine to me. I would still recommend using `neat_json_send_once` directly instead of duplicating that function. The existing code might assume that all callbacks are specified, but this can be easily changed.

**Comment by karlgrin** [comment]
@oystedal I am willing to refactor the could so that it uses neat_json_send_once, however, I am not sure I completely follow you on how to do that. Maybe, I will contact you on this.

**Comment by oystedal** [comment]
My code in neat_pm_socket.c assumes that the callbacks given in the call to neat_json_send_once are not NULL. This is not necessary for the CIB feedback mechanism. My suggestion is to add an if-statement to check for this where the callbacks are called, so that neat_json_send_once can be called with no callbacks.

**Comment by karlgrin** [comment]
@oystedal  I'll try to fix this this or next week.

**Comment by karlgrin** [comment]
@bozakov @oystedal Ok. So, is this something that ended on my plate, or did you conclude that the error originates from something else?

**Comment by bozakov** [comment]
@karlgrin I only undid the changes that add the candidate properties to the JSON structure. Sorry for the premature merge. I think you would be best suited to identify what was going wrong there.

**Pull request merged**
