### PR TITLE
RPM packaging for NEAT

### PR DESCRIPTION
**Pull request by dreibh**
This pull request adds the necessary files and helper scripts for building NEAT RPM packages (e.g. Fedora Core). I now provide up-to-date NEAT package repositories for Fedora 23, 24, and 25, each for i386 and x86_64 at https://packages.nntb.no/nornet-applications/fedora/ .

### CODE REVIEW

**Comment by dreibh** [comment]
FYI: the mentioned RPM package repository is of course used by NorNet Core slices as well. So, when using NorNet Core, enjoying NEAT software just requires a "sudo dnf install libneat-examples" (or libneat-devel, etc.) call to get everything installed.

For information on NorNet Core, see: https://www.nntb.no/ . The current site list can be found here: https://www.nntb.no/pub/nornet-configuration/NorNetCore-Sites.html .

**Comment by weinrank** [comment]
I don't know anything about building RPM packages, is it useful and possible to integrate a test into the buildbot environment to test the generation?

**Comment by dreibh** [comment]
Hi,

Fredag 2. desember 2016 14.23.56 skrev Felix Weinrank:
> I don't know anything about building RPM packages, is it useful and possible to integrate a test into the buildbot environment to test the generation?

This should be no problem. It depends on your build bots, of course.

If you have a Fedora x86_64 installation, you can call the script "make-rpm" to build for a certain variant, e.g.:
./make-rpm fedora-24-x86_64
or
./make-rpm fedora-25-i386

Internally, the script calls "mock" (which is similar to "pbuilder" on Debian/Ubuntu).

-- 
Best regards / Mit freundlichen Grüßen / Med vennlig hilsen

=======================================================================
 Thomas Dreibholz

 Simula Research Laboratory
 Simula Innovation AS, Network Systems Group
 Visiting address: Martin Linges vei 17, 1364 Fornebu, Norway
 Mailing address:  P.O.Box 134, 1325 Lysaker, Norway
-----------------------------------------------------------------------
 E-Mail:     dreibh@simula.no
 Homepage:   http://simula.no/people/dreibh
=======================================================================

**Comment by weinrank** [comment]
We don't have Fedora buildslaves, only Ubuntu 16.10...

**Comment by dreibh** [comment]
It would be possible to provide a Fedora VM for build test purposes, of course.

**Comment by dreibh** [comment]
Working with latest "master" branch now. Is anything more needed to merge this pull request?

**Pull request merged**
