### PR TITLE
More strict compiler flags

### PR DESCRIPTION
**Pull request by weinrank**
- -Wfloat-equal
- -Wshadow
- -Wpointer-arith
- -Wunreachable-code
- -Winit-self

### CODE REVIEW

**Comment by dreibh** [comment]
The pull request is useful. The stricter options also work with the NEAT Sockets API branch.

**Comment by bagder** [comment]
My only remark, which already existed, is that I can't see any checks that these options actually work with the used compiler.

**Comment by weinrank** [comment]
@bagder I've no experience in checking that the compiler supports the checks. Any hints?

**Comment by bagder** [comment]
I'm a cmake illiterate so I'm not much good for the actually writing this (I've done my time in the autotools school). But the general idea would be to either

1. test-build a basic source snippet with the compiler option(s) you intend to enable OR
2. check which compiler you use, which version it has, and then enable the compiler options for this combination that you know works

**Pull request merged**
