### PR TITLE
Support for multistreaming with SCTP

### PR DESCRIPTION
**Pull request by oystedal**
This PR adds support for multistreaming over SCTP.

* For now, I have assumed that the number of streams are symmetric in both directions.
* Down the line I think we should consider storing an `on_writable` callback for each stream, instead of forcing applications to use the same callback for all streams.

I have added a separate server/client example for multistreaming. We may consider integrating this with the existing server_echo and client respectively in the future.

@tuexen: I suppose you should take a look at this PR. In particular, I have had difficulties finding a documented way of getting the association id for a given socket/fd. [This](https://github.com/NEAT-project/neat/compare/oystedal/multistream?diff=unified&expand=1&name=oystedal%2Fmultistream#diff-4ec7caa7f7478f502be1c62255bbb75fR1151) is how I've done it so far, which appears to work.

### CODE REVIEW

**Comment by tuexen** [comment]
My understanding is that we use only one-to-one style SCTP sockets. So there is no need to deal with association ids. Why do you need this?

**Comment by oystedal** [comment]
I see, then I've misunderstood the concept of one-to-many sockets being related to multistreaming as well. I'll update the code tomorrow.

**Comment by mcmanus** [comment]
As I understood this issue from Aberdeen - multistreaming was generally supposed to be transparent to the API (i.e. not necessarily one to one, but that was transparent to the caller). A couple use cases were identified where that wasn't going to work, so we were going to provide a second-class API (ala setsockopt) for creating the binding only when necessary.

maybe I'm not remembering correctly?

**Comment by tuexen** [comment]
My understanding:
* Allow applications to explicitly use SCTP streams, if they want. This means that they require SCTP as the protocol and use a specific API.
* Later, allow the transparent mapping of neat flows to multiple TCP connection or SCTP streams.
I think we discussed the second, but I would not prevent the user from doing the first.

**Comment by mwelzl** [comment]
exactly

**Comment by weinrank** [comment]
I suggest that you integrate the multistream feature in the existing client and echo_server and make it configurable by command line options.

**Comment by oystedal** [comment]
I agree. It's on my todo list, just not a high priority atm.

**Pull request merged**
