### PR TITLE
Enable listening to multiple sockets

### PR DESCRIPTION
**Pull request by oystedal**
Quite a sizeable patch, but this allow a server to listen to multiple sockets~~, one for each protocol~~. 

- I have added a new struct, neat_pollable_socket (nps), which contains socket-specific data, such as fd, stack, family, type, addrs, and internal data.
- neat_flow has been refactored to include one nps for communication, and a linked list of
nps for listening. A flow will use either the list or the nps for communication, not both.
- Several functions refactored to include a pointer to an nps: io_readable, do_accept, etc.
- The libuv handle used in uvpollable_cb now contains a pointer to a nps in its data field, instead of a pointer to a flow previously.
- USRSCTP code has been mostly updated to use neat_pollable_socket.
- UDP encapsulation of SCTP has been disabled in accept_resolve_cb, since it currently interferes with "listening" on the other UDP socket if present. I understand there's a UDP port for encapsulation, which we can use in this case. How do I specify the SCTP port when using UDP encapsulation? @tuexen: Do you have any suggestions on how to handle this?
- Write/read size should be moved to nps, but this isn't critical.
- neat_listen_via_kernel_ex will eventually replace neat_listen_via_kernel.

### CODE REVIEW

**Comment by tuexen** [comment]
Does this mean that a server can't listen on multiple addresses for the same protocol? How do you envision to support SCTP endpoints listening on multiple IP addresses?
I don't understand the question regarding UDP encapsulation? The user of the SCTP stack (kernel or userland) doesn't see the UDP socket at all. It always looks like a normal SCTP socket. UDP encapsulation is enabled via a socket option. In case of a kernel implementation, the kernel completely deals with the UDP handling. There is no UDP socket exposed to the applications. In case of a userland stack, UDP encapsulated packets are just provided to the stack via an additional input method. Similar to IPv4 and IPv6. I don't see why UDP encapsulation must be disabled. The neat code must head with the case that UDP sockets are bound by other processes anyway.

**Comment by oystedal** [comment]
> Does this mean that a server can't listen on multiple addresses for the same protocol?

The code can (and most likely should) be updated so that it can listen on multiple addresses. This should only require modifications in `accept_resolve_cb` such that all local addresses are enumerated and listened on. Apart from this, there's no hard limitation on having only one socket per protocol, so this shouldn't be problematic to implement.

> The user of the SCTP stack (kernel or userland) doesn't see the UDP socket at all. It always looks like a normal SCTP socket. UDP encapsulation is enabled via a socket option.

Thanks for clearing this up. When I tested listening on SCTP, UDP, and SCTP/UDP, I got EADDRINUSE, which I wrongly assumed was because the UDP and SCTP/UDP would use the same port. Thus, if I understand correctly, you can't have an SCTP and an SCTP/UDP socket bound to the same port. In this case, does an SCTP/UDP socket allow for communication both with and without encapsulation?

In either case, I'll update the code to not disallow SCTP/UDP.

**Comment by tuexen** [comment]
The SCTP port number space and the UDP port number space are independent. UDP encaps uses most likely UDP port 9899 (that is the IANA assigned one). As long as you don't use the same port for pure UDP communication, you should be fine. However, it makes sense to trace down why you go an error.

**Comment by oystedal** [comment]
Ah, I see now. I was under the impression that enabling UDP encapsulation would exclude non-encapsulated SCTP connections, but this isn't the case. Sorry for creating confusion.

**Comment by oystedal** [comment]
> Does this mean that a server can't listen on multiple addresses for the same protocol? How do you envision to support SCTP endpoints listening on multiple IP addresses?

Unless the optional argument `local_name` is specified to `neat_accept`, it will listen on all available local addresses (i.e. IPv4 address 0.0.0.0). If you specify a local name, the resolved address will be used for listening. AFAICS, this should allow any protocol to listen on all local addresses on a machine.

If we want to support listening to a proper subset of the available addresses, we would have to change `neat_accept` such that

1.  it may be called multiple times on a flow, and
2.  it does not operate on any variables in the neat_flow struct, since these must be independent of all sockets on a flow used to accept incoming connections.

If this is a use case we want to support, then I'll make the necessary changes.

**Comment by tuexen** [comment]
I would expect that local_name could be a comma separated list of IP-addresses (at least for SCTP) and you would use sctp_bindx() to bind to them. At least in the future...

**Pull request merged**
